change backend and formalize the dir_names
fitchgroup/Vocel pull request #16
Opened 2023-05-16 00:23 UTC by pyangyu

I rearranged the files and worked on the backends. I was developing the codes to make use of AmplifyDataStore and AmplifyAPI.

2023-05-16 00:40 UTC, pyangyu commented
I rearranged the files and add some localization configurations, and the functionalities of the code do not change (except for some backend configurations, I tried to connect the announcement data to the backend, and probably will finish it these two days).

2023-05-16 15:24 UTC, JavaDerek requested changes
Please make requested changes

2023-05-16 15:24 UTC, JavaDerek commented on lib/LocalizedButtonResolver.dart
> +  // @override
Remove commented code

2023-05-16 15:24 UTC, JavaDerek commented on lib/LocalizedButtonResolver.dart
> +  // String submit(BuildContext context) {
Remove commented code

2023-05-16 15:24 UTC, JavaDerek commented on lib/features/announcement/controller/announcement_list_controller.dart
> +      isPin: false
change to "isPinned"

2023-05-16 15:24 UTC, JavaDerek commented on lib/features/announcement/ui/drawer_list/bottom_navigation.dart
> +  // Future<List> fetchGroups() async {
remove commented code

2023-05-16 15:24 UTC, JavaDerek commented on lib/features/announcement/ui/home_page/announcement_list.dart
> +class Reminder {
Remove unused classes and break used ones into separate files, please

2023-05-16 15:24 UTC, JavaDerek commented on lib/features/announcement/ui/home_page/notes.dart
> +// import 'package:vocel/features/announcement/ui/home_page/add_announcement_bottomsheet.dart';
why add something commented?

2023-05-16 15:24 UTC, JavaDerek commented on lib/features/announcement/ui/setting_page/language_list.dart
> +        // DropdownButton<Language>(
remove commented code

2023-05-24 15:05 UTC, JavaDerek approved these changes

2023-05-30 16:12 UTC, erie149 approved these changes

2023-05-30 16:13 UTC, merged